name: Optimize map and deploy

on: [push]

permissions:
  contents: write
  pages: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: "Install dependencies"
        run: npm install

      - name: "Build scripts"
        run: npm run build

      # - name: Use API key from secrets
      #   env:
      #     MAP_STORAGE_API_KEY: ${{ secrets.MAP_STORAGE_API_KEY }}
      #   run: echo "MAP_STORAGE_API_KEY=${MAP_STORAGE_API_KEY}" >> $GITHUB_ENV

      # - name: Use URL Map STORAGE from secrets
      #   env:
      #     URL_MAP_STORAGE: ${{ secrets.URL_MAP_STORAGE }}
      #   run: echo "URL_MAP_STORAGE=${URL_MAP_STORAGE}" >> $GITHUB_ENV

      # - name: Generate .env.secret
      #   run: echo "MAP_STORAGE_API_KEY=${{ secrets.MAP_STORAGE_API_KEY }}" > .env.secret

      # - name: Extract UPLOAD_MODE from .env
      #   run: echo "UPLOAD_MODE=$(grep UPLOAD_MODE .env | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Deploy in MAP STORAGE
        #i f: ${{ env.UPLOAD_MODE == 'MAP_STORAGE' }}
        run: npm run upload-only

      - name: Deploy on GITHUB PAGES
        #i f: ${{ env.UPLOAD_MODE == 'GH_PAGES' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
